services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - build:/app/build
    command: gleam run

  dev:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - build:/app/build
    command: sh
    stdin_open: true
    tty: true

volumes:
  build:
