name = "api2spec_fixture_gleam"
version = "0.1.0"

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_http = "~> 3.6"
gleam_json = "~> 1.0"
mist = "~> 1.0"
wisp = "~> 0.14"

[dev-dependencies]
gleeunit = "~> 1.0"
