openapi: 3.0.3
info:
  title: API
  version: 1.0.0
paths:
  /health:
    get:
      tags:
        - health
      operationId: getHealth_handler
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /health/ready:
    get:
      tags:
        - health
      operationId: getReady_handler
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /posts:
    get:
      tags:
        - posts
      operationId: getPosts_handler
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      tags:
        - posts
      operationId: postPosts_handler
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /posts/{id}:
    get:
      tags:
        - posts
      operationId: getPost_handler
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /users:
    get:
      tags:
        - users
      operationId: getUsers_handler
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
    post:
      tags:
        - users
      operationId: postUsers_handler
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /users/{id}:
    get:
      tags:
        - users
      operationId: getUser_handler
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
    put:
      tags:
        - users
      operationId: putUser_handler
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
    delete:
      tags:
        - users
      operationId: deleteUser_handler
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
  /users/{user_id}/posts:
    get:
      tags:
        - users
      operationId: getUser_posts_handler
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
        "400":
          description: Bad request
        "500":
          description: Internal server error
